# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1468, 768)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1471, 768))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.menuKismi = QtWidgets.QFrame(self.frame)
        self.menuKismi.setEnabled(True)
        self.menuKismi.setGeometry(QtCore.QRect(0, 0, 1471, 140))
        self.menuKismi.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.menuKismi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuKismi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuKismi.setObjectName("menuKismi")
        self.labelid = QtWidgets.QLabel(self.menuKismi)
        self.labelid.setGeometry(QtCore.QRect(110, 100, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelid.setFont(font)
        self.labelid.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.labelid.setObjectName("labelid")
        self.labelAdSoyad = QtWidgets.QLabel(self.menuKismi)
        self.labelAdSoyad.setGeometry(QtCore.QRect(110, 10, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAdSoyad.setFont(font)
        self.labelAdSoyad.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.labelAdSoyad.setObjectName("labelAdSoyad")
        self.labelizin = QtWidgets.QLabel(self.menuKismi)
        self.labelizin.setGeometry(QtCore.QRect(110, 70, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelizin.setFont(font)
        self.labelizin.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.labelizin.setObjectName("labelizin")
        self.labelGirisCikis = QtWidgets.QLabel(self.menuKismi)
        self.labelGirisCikis.setGeometry(QtCore.QRect(110, 40, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelGirisCikis.setFont(font)
        self.labelGirisCikis.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.labelGirisCikis.setObjectName("labelGirisCikis")
        self.lbl_AdSoyad = QtWidgets.QLabel(self.menuKismi)
        self.lbl_AdSoyad.setGeometry(QtCore.QRect(250, 10, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_AdSoyad.setFont(font)
        self.lbl_AdSoyad.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.lbl_AdSoyad.setObjectName("lbl_AdSoyad")
        self.lbl_izinli = QtWidgets.QLabel(self.menuKismi)
        self.lbl_izinli.setGeometry(QtCore.QRect(250, 70, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_izinli.setFont(font)
        self.lbl_izinli.setStyleSheet("color: rgb(0, 170, 0);\n"
"")
        self.lbl_izinli.setObjectName("lbl_izinli")
        self.lblGiris = QtWidgets.QLabel(self.menuKismi)
        self.lblGiris.setGeometry(QtCore.QRect(250, 40, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblGiris.setFont(font)
        self.lblGiris.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.lblGiris.setObjectName("lblGiris")
        self.lbl_ID = QtWidgets.QLabel(self.menuKismi)
        self.lbl_ID.setGeometry(QtCore.QRect(250, 100, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_ID.setFont(font)
        self.lbl_ID.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.lbl_ID.setObjectName("lbl_ID")
        self.btnKisiler = QtWidgets.QPushButton(self.menuKismi)
        self.btnKisiler.setGeometry(QtCore.QRect(1175, 20, 80, 80))
        self.btnKisiler.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnKisiler.setAutoFillBackground(False)
        self.btnKisiler.setStyleSheet("border:0px")
        self.btnKisiler.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resimler/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKisiler.setIcon(icon)
        self.btnKisiler.setIconSize(QtCore.QSize(80, 80))
        self.btnKisiler.setObjectName("btnKisiler")
        self.btnKisiEkle = QtWidgets.QPushButton(self.menuKismi)
        self.btnKisiEkle.setGeometry(QtCore.QRect(1375, 20, 80, 80))
        self.btnKisiEkle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnKisiEkle.setAutoFillBackground(False)
        self.btnKisiEkle.setStyleSheet("border:0px")
        self.btnKisiEkle.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resimler/add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKisiEkle.setIcon(icon1)
        self.btnKisiEkle.setIconSize(QtCore.QSize(80, 80))
        self.btnKisiEkle.setObjectName("btnKisiEkle")
        self.label_kisiler = QtWidgets.QLabel(self.menuKismi)
        self.label_kisiler.setGeometry(QtCore.QRect(1180, 97, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_kisiler.setFont(font)
        self.label_kisiler.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_kisiler.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kisiler.setObjectName("label_kisiler")
        self.label_kayit = QtWidgets.QLabel(self.menuKismi)
        self.label_kayit.setGeometry(QtCore.QRect(1280, 97, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_kayit.setFont(font)
        self.label_kayit.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_kayit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kayit.setObjectName("label_kayit")
        self.label_kisiEkle = QtWidgets.QLabel(self.menuKismi)
        self.label_kisiEkle.setGeometry(QtCore.QRect(1380, 97, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_kisiEkle.setFont(font)
        self.label_kisiEkle.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_kisiEkle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kisiEkle.setObjectName("label_kisiEkle")
        self.btnKayit = QtWidgets.QPushButton(self.menuKismi)
        self.btnKayit.setGeometry(QtCore.QRect(1275, 20, 80, 80))
        self.btnKayit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnKayit.setAutoFillBackground(False)
        self.btnKayit.setStyleSheet("border:0px")
        self.btnKayit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resimler/kayit2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKayit.setIcon(icon2)
        self.btnKayit.setIconSize(QtCore.QSize(80, 80))
        self.btnKayit.setObjectName("btnKayit")
        self.lblProfilFoto = QtWidgets.QLabel(self.menuKismi)
        self.lblProfilFoto.setGeometry(QtCore.QRect(10, 20, 100, 100))
        self.lblProfilFoto.setAutoFillBackground(False)
        self.lblProfilFoto.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.lblProfilFoto.setText("")
        self.lblProfilFoto.setPixmap(QtGui.QPixmap("resimler/personReal.png"))
        self.lblProfilFoto.setScaledContents(True)
        self.lblProfilFoto.setObjectName("lblProfilFoto")
        self.control_bt = QtWidgets.QPushButton(self.menuKismi)
        self.control_bt.setGeometry(QtCore.QRect(1075, 20, 80, 80))
        self.control_bt.setStyleSheet("border:0px\n"
"")
        self.control_bt.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resimler/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.control_bt.setIcon(icon3)
        self.control_bt.setIconSize(QtCore.QSize(80, 80))
        self.control_bt.setObjectName("control_bt")
        self.label_kisiler_2 = QtWidgets.QLabel(self.menuKismi)
        self.label_kisiler_2.setGeometry(QtCore.QRect(1080, 97, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_kisiler_2.setFont(font)
        self.label_kisiler_2.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_kisiler_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kisiler_2.setObjectName("label_kisiler_2")
        self.labelid.raise_()
        self.labelAdSoyad.raise_()
        self.labelizin.raise_()
        self.labelGirisCikis.raise_()
        self.lbl_AdSoyad.raise_()
        self.lbl_ID.raise_()
        self.btnKisiler.raise_()
        self.btnKisiEkle.raise_()
        self.label_kisiler.raise_()
        self.label_kayit.raise_()
        self.label_kisiEkle.raise_()
        self.btnKayit.raise_()
        self.lblProfilFoto.raise_()
        self.control_bt.raise_()
        self.lbl_izinli.raise_()
        self.lblGiris.raise_()
        self.label_kisiler_2.raise_()
        self.altFrame = QtWidgets.QFrame(self.frame)
        self.altFrame.setGeometry(QtCore.QRect(0, 140, 1470, 628))
        self.altFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altFrame.setObjectName("altFrame")
        self.frame_2 = QtWidgets.QFrame(self.altFrame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 800, 628))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.image_label = QtWidgets.QLabel(self.frame_2)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 800, 628))
        self.image_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image_label.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.kayitFrame = QtWidgets.QFrame(self.altFrame)
        self.kayitFrame.setGeometry(QtCore.QRect(800, 0, 671, 628))
        self.kayitFrame.setStyleSheet("")
        self.kayitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kayitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kayitFrame.setObjectName("kayitFrame")
        self.tableWidget = QtWidgets.QTableWidget(self.kayitFrame)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 671, 628))
        self.tableWidget.setStyleSheet("selection-background-color: rgb(233, 185, 110);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.lbl_AdSoyad.setBuddy(self.btnKisiler)
        self.lblProfilFoto.setBuddy(self.btnKisiler)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.control_bt, self.btnKisiler)
        Form.setTabOrder(self.btnKisiler, self.btnKayit)
        Form.setTabOrder(self.btnKayit, self.btnKisiEkle)
        Form.setTabOrder(self.btnKisiEkle, self.tableWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.labelid.setText(_translate("Form", "ID :"))
        self.labelAdSoyad.setText(_translate("Form", "Ad Soyad :"))
        self.labelizin.setText(_translate("Form", "İzin Durumu :"))
        self.labelGirisCikis.setText(_translate("Form", "<html><head/><body><p>Giriş / Çıkış :</p></body></html>"))
        self.lbl_AdSoyad.setText(_translate("Form", "Ad Soyadi"))
        self.lbl_izinli.setText(_translate("Form", "İzinli"))
        self.lblGiris.setText(_translate("Form", "Giriş"))
        self.lbl_ID.setText(_translate("Form", "Id Numarasi"))
        self.label_kisiler.setText(_translate("Form", "Kişiler"))
        self.label_kayit.setText(_translate("Form", "Kayıtlar"))
        self.label_kisiEkle.setText(_translate("Form", "Kişi Ekle"))
        self.label_kisiler_2.setText(_translate("Form", "Başlat"))
        self.image_label.setText(_translate("Form", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "İzin Durumu"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Giriş/Çıkış"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Soyad"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Tarih"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Saat"))



